version: "3"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: assessment
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    networks:
      - app-net
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    networks:
      - app-net

volumes:
  pgdata:

networks:
  app-net:
    driver: bridge
